_src/9/myfaves/config/routes.rb
Myfaves2::Application.routes.draw do
  resources :artists

  resources :myfaves
  
  

  root :to => "myfaves#index"

end

_src/9/myfaves/app/models/artist.rb
class Artist < ActiveRecord::Base
  searchable do
    text :name, :default_boost => 2
    string :group_type
#    time :release_date
  end
end

_src/9/myfaves/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

_src/9/myfaves/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.xml
  def index
    if params[:q]
      @artists = Artist.search{ keywords params[:q]}.results
    else
      @artists = Artist.paginate :page => params[:page], :order => 'created_at DESC'
    end
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @artists }
      format.json { render :json => @artists.to_json(:only => [:name, :id]), :callback => params[:callback] }
      
    end
  end

  # GET /artists/1
  # GET /artists/1.xml
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.xml
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.xml
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to(@artist, :notice => 'Artist was successfully created.') }
        format.xml  { render :xml => @artist, :status => :created, :location => @artist }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.xml
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to(@artist, :notice => 'Artist was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @artist.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.xml
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to(artists_url) }
      format.xml  { head :ok }
    end
  end
end

_src/9/myfaves/app/controllers/myfaves_controller.rb
require 'uri'
class MyfavesController < ApplicationController
  before_filter :myfaves
  def index

  end

  def create
    begin
      @artist = Artist.find(params[:artist][:id])
    rescue ActiveRecord::RecordNotFound
    end
    
    if @artist.nil?
      flash[:notice] = "Artist matching #{params[:artist][:name]} was not found."
    else
      if @artist.image_url.nil?
        @artist.image_url = find_artist_image(@artist.name)
        @artist.save!
      end
      @myfaves << @artist
      @myfaves.uniq!
    end

    redirect_to :action => :index
    
  end

  def show
    #fixme this shoudl be a destroy method not a show method!
    @artist = Artist.find(params[:id])

    @myfaves.delete @artist

    redirect_to :action => :index
  end  
  
protected
  def myfaves
    unless session[:myfaves]
      session[:myfaves] = []
    end
    @myfaves = session[:myfaves]    
  end
  
  def find_artist_image(name)
    name = URI.escape(name)

    resp = Net::HTTP.get_response(URI.parse("http://ajax.googleapis.com/ajax/services/search/images?v=1.0&q=#{name}"))

    result = ActiveSupport::JSON.decode(resp.body)    
      
    return result['responseData']['results'].first['url'] unless result['responseData']['results'].size == 0

  end
end

_src/9/myfaves/app/helpers/application_helper.rb
module ApplicationHelper
end

_src/9/myfaves/app/helpers/artists_helper.rb
module ArtistsHelper
end

_src/9/myfaves/app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group_type %><br />
    <%= f.text_field :group_type %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br />
    <%= f.text_field :release_date %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

_src/9/myfaves/app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

_src/9/myfaves/app/views/artists/index.html.erb
<h1>Listing artists</h1>

<%= will_paginate @artists %>

<table>
  <tr>
    <th>Name</th>
    <th>Group type</th>
    <th>Release date</th>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artists.each do |artist| %>
  <tr>
    <td><%= artist.name %></td>
    <td><%= artist.group_type %></td>
    <td><%= artist.release_date %></td>
    <td><%= artist.image_url %></td>
    <td><%= link_to 'Show', artist %></td>
    <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    <td><%= link_to 'Destroy', artist, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artist', new_artist_path %>

_src/9/myfaves/app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

_src/9/myfaves/app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @artist.name %>
</p>

<p>
  <b>Group type:</b>
  <%= @artist.group_type %>
</p>

<p>
  <b>Release date:</b>
  <%= @artist.release_date %>
</p>

<p>
  <b>Image url:</b>
  <%= @artist.image_url %>
</p>


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

_src/9/myfaves/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myfaves2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

_src/9/myfaves/app/views/layouts/artists.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Artists: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

_src/9/myfaves/app/views/layouts/myfaves.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>MyFaves: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
  <script type="text/javascript" src="http://view.jquery.com/trunk/plugins/autocomplete/lib/jquery.js"></script>
  <script type='text/javascript' src='http://view.jquery.com/trunk/plugins/autocomplete/lib/jquery.bgiframe.min.js'></script>
  <script type='text/javascript' src='http://view.jquery.com/trunk/plugins/autocomplete/lib/jquery.ajaxQueue.js'></script>
  <script type='text/javascript' src='http://view.jquery.com/trunk/plugins/autocomplete/jquery.autocomplete.js'></script>

  <link rel="stylesheet" type="text/css" href="http://view.jquery.com/trunk/plugins/autocomplete/demo/main.css" />
  <%= stylesheet_link_tag 'jquery.autocomplete' %>
  


</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>


</body>
</html>

_src/9/myfaves/app/views/myfaves/_artist.html.erb
<% if artist_counter % 4 == 0 %>
<tr>
<% end %>
<td align="center">
<% if artist.image_url %>
<%= image_tag(artist.image_url, :border=>0)%>
<% end %>
<p>
<%= artist.name %>  |<%= link_to 'X',  {:action=>"destroy", :controller=>"myfaves", :id=>artist.id}, :confirm => "Are you sure you want to remove #{artist.name} from your favorites?", :method => :delete %>|
</p>
</td>
<% if artist_counter % 4 == 3 %>
</tr>
<% end %>

_src/9/myfaves/app/views/myfaves/index.html.erb
<script type="text/javascript">
$(function() {

	function formatForDisplay(doc) {
		return doc.artist.name;
	}

	$("#artist_name").autocomplete( '/artists.json?callback=?', {
		dataType: "jsonp",
		width: 300,
		minChars: 2,
		parse: function(data) {
		  $("#artist_id").get(0).value = "";  // clear out hidden field
			return $.map(data, function(doc) {
				return {
					data: doc,
					value: doc.artist.id.toString(),
					result: doc.artist.name
				}
			});
		},
		formatItem: function(doc) {
			return formatForDisplay(doc);
		}
	}).result(function(e, doc) {
	  $("#artist_id").get(0).value = doc.artist.id;
		$("#content").append("<p>selected " + formatForDisplay(doc) + "(" + doc.artist.id + ")" + "</p>");
	});
});

</script>

<h1>My Favorite Artists</h1>


<table border = 1>
<%= render(:partial => 'artist', :collection => @myfaves, :spacer_template => 'spacer') %>   
</table>

<br />
<%= form_for :artist do |f| %> 
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <%= f.hidden_field :id %>
  </p>
  <p>
    <%= f.submit 'Add' %>
  </p>
  <p>
  </p>
<% end %>
<p/>
<hr/>
<%= link_to 'All Artists', artists_path %>